ALTER TABLE groups ADD COLUMN scout_group TEXT NOT NULL DEFAULT '';
ALTER TABLE groups ADD COLUMN members TEXT NOT NULL DEFAULT '';
ALTER TABLE groups ADD COLUMN phone_number TEXT NOT NULL DEFAULT '';
